from __future__ import annotations

from core.registry.models import MetricSpec, ResourceTypeSpec

_M = MetricSpec

AWS_RESOURCE_TYPES: list[ResourceTypeSpec] = [
    ResourceTypeSpec(
        type_id="AWS::EC2::Instance",
        cloud="aws",
        display_name="EC2 Instance",
        service="Compute",
        metrics=(
            _M("CPUUtilization", "AWS/EC2", "Average", "InstanceId"),
            _M("NetworkOut", "AWS/EC2", "Sum", "InstanceId"),
            _M("NetworkIn", "AWS/EC2", "Sum", "InstanceId"),
        ),
        typical_monthly_cost_usd=50.0,
        docs_url="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/",
    ),
    ResourceTypeSpec(
        type_id="AWS::RDS::DBInstance",
        cloud="aws",
        display_name="RDS Instance",
        service="Database",
        metrics=(
            _M("CPUUtilization", "AWS/RDS", "Average", "DBInstanceIdentifier"),
            _M("DatabaseConnections", "AWS/RDS", "Average", "DBInstanceIdentifier"),
            _M("NetworkReceiveThroughput", "AWS/RDS", "Sum", "DBInstanceIdentifier"),
        ),
        typical_monthly_cost_usd=150.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::RDS::DBCluster",
        cloud="aws",
        display_name="Aurora DB Cluster",
        service="Database",
        metrics=(
            _M("CPUUtilization", "AWS/RDS", "Average", "DBClusterIdentifier"),
            _M("DatabaseConnections", "AWS/RDS", "Average", "DBClusterIdentifier"),
            _M("AuroraReplicaLag", "AWS/RDS", "Average", "DBClusterIdentifier"),
        ),
        typical_monthly_cost_usd=200.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::EC2::NatGateway",
        cloud="aws",
        display_name="NAT Gateway",
        service="Networking",
        metrics=(
            _M("BytesOutToDestination", "AWS/NatGateway", "Sum", "NatGatewayId"),
            _M("BytesInFromDestination", "AWS/NatGateway", "Sum", "NatGatewayId"),
            _M("PacketsOutToDestination", "AWS/NatGateway", "Sum", "NatGatewayId"),
        ),
        typical_monthly_cost_usd=32.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::ElasticLoadBalancingV2::LoadBalancer",
        cloud="aws",
        display_name="Application/Network Load Balancer",
        service="Networking",
        metrics=(
            _M("RequestCount", "AWS/ApplicationELB", "Sum", "LoadBalancer"),
            _M("ActiveConnectionCount", "AWS/ApplicationELB", "Sum", "LoadBalancer"),
            _M("TargetResponseTime", "AWS/ApplicationELB", "Average", "LoadBalancer"),
        ),
        typical_monthly_cost_usd=20.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::ElasticLoadBalancing::LoadBalancer",
        cloud="aws",
        display_name="Classic Load Balancer",
        service="Networking",
        metrics=(
            _M("RequestCount", "AWS/ELB", "Sum", "LoadBalancerName"),
            _M("HealthyHostCount", "AWS/ELB", "Average", "LoadBalancerName"),
            _M("UnHealthyHostCount", "AWS/ELB", "Average", "LoadBalancerName"),
        ),
        typical_monthly_cost_usd=18.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::Lambda::Function",
        cloud="aws",
        display_name="Lambda Function",
        service="Compute",
        metrics=(
            _M("Invocations", "AWS/Lambda", "Sum", "FunctionName"),
            _M("Duration", "AWS/Lambda", "Average", "FunctionName"),
            _M("Errors", "AWS/Lambda", "Sum", "FunctionName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::EC2::Volume",
        cloud="aws",
        display_name="EBS Volume",
        service="Storage",
        metrics=(
            _M("VolumeReadOps", "AWS/EBS", "Sum", "VolumeId"),
            _M("VolumeWriteOps", "AWS/EBS", "Sum", "VolumeId"),
            _M("VolumeReadBytes", "AWS/EBS", "Sum", "VolumeId"),
        ),
        typical_monthly_cost_usd=10.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::DynamoDB::Table",
        cloud="aws",
        display_name="DynamoDB Table",
        service="Database",
        metrics=(
            _M("ConsumedReadCapacityUnits", "AWS/DynamoDB", "Sum", "TableName"),
            _M("ConsumedWriteCapacityUnits", "AWS/DynamoDB", "Sum", "TableName"),
            _M("SuccessfulRequestLatency", "AWS/DynamoDB", "Average", "TableName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::SQS::Queue",
        cloud="aws",
        display_name="SQS Queue",
        service="Messaging",
        metrics=(
            _M("NumberOfMessagesSent", "AWS/SQS", "Sum", "QueueName"),
            _M("NumberOfMessagesReceived", "AWS/SQS", "Sum", "QueueName"),
            _M("ApproximateNumberOfMessagesVisible", "AWS/SQS", "Average", "QueueName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::ElastiCache::CacheCluster",
        cloud="aws",
        display_name="ElastiCache Cluster",
        service="Cache",
        metrics=(
            _M("CPUUtilization", "AWS/ElastiCache", "Average", "CacheClusterId"),
            _M("CurrConnections", "AWS/ElastiCache", "Average", "CacheClusterId"),
            _M("CacheHits", "AWS/ElastiCache", "Sum", "CacheClusterId"),
        ),
        typical_monthly_cost_usd=60.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::ElastiCache::ReplicationGroup",
        cloud="aws",
        display_name="ElastiCache Replication Group",
        service="Cache",
        metrics=(
            _M("CurrConnections", "AWS/ElastiCache", "Average", "ReplicationGroupId"),
            _M("CacheHitRate", "AWS/ElastiCache", "Average", "ReplicationGroupId"),
            _M("ReplicationLag", "AWS/ElastiCache", "Average", "ReplicationGroupId"),
        ),
        typical_monthly_cost_usd=120.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::Redshift::Cluster",
        cloud="aws",
        display_name="Redshift Cluster",
        service="Analytics",
        metrics=(
            _M("CPUUtilization", "AWS/Redshift", "Average", "ClusterIdentifier"),
            _M("DatabaseConnections", "AWS/Redshift", "Average", "ClusterIdentifier"),
            _M("ReadIOPS", "AWS/Redshift", "Average", "ClusterIdentifier"),
        ),
        typical_monthly_cost_usd=300.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::OpenSearchService::Domain",
        cloud="aws",
        display_name="OpenSearch Domain",
        service="Analytics",
        metrics=(
            _M("CPUUtilization", "AWS/ES", "Average", "DomainName"),
            _M("SearchableDocuments", "AWS/ES", "Average", "DomainName"),
            _M("IndexingRate", "AWS/ES", "Average", "DomainName"),
        ),
        typical_monthly_cost_usd=180.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::ECS::Service",
        cloud="aws",
        display_name="ECS Service",
        service="Compute",
        metrics=(
            _M("CPUUtilization", "AWS/ECS", "Average", "ServiceName"),
            _M("MemoryUtilization", "AWS/ECS", "Average", "ServiceName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::EKS::Cluster",
        cloud="aws",
        display_name="EKS Cluster",
        service="Compute",
        metrics=(
            _M("cluster_node_count", "ContainerInsights", "Average", "ClusterName"),
            _M("node_cpu_utilization", "ContainerInsights", "Average", "ClusterName"),
            _M("node_memory_utilization", "ContainerInsights", "Average", "ClusterName"),
        ),
        typical_monthly_cost_usd=73.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::Kinesis::Stream",
        cloud="aws",
        display_name="Kinesis Data Stream",
        service="Streaming",
        metrics=(
            _M("GetRecords.Records", "AWS/Kinesis", "Sum", "StreamName"),
            _M("IncomingRecords", "AWS/Kinesis", "Sum", "StreamName"),
            _M("PutRecord.Success", "AWS/Kinesis", "Sum", "StreamName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::SNS::Topic",
        cloud="aws",
        display_name="SNS Topic",
        service="Messaging",
        metrics=(
            _M("NumberOfNotificationsDelivered", "AWS/SNS", "Sum", "TopicName"),
            _M("NumberOfMessagesPublished", "AWS/SNS", "Sum", "TopicName"),
            _M("NumberOfNotificationsFailed", "AWS/SNS", "Sum", "TopicName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::ApiGateway::RestApi",
        cloud="aws",
        display_name="API Gateway REST API",
        service="API",
        metrics=(
            _M("Count", "AWS/ApiGateway", "Sum", "ApiName"),
            _M("4XXError", "AWS/ApiGateway", "Sum", "ApiName"),
            _M("5XXError", "AWS/ApiGateway", "Sum", "ApiName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::ApiGateway::Stage",
        cloud="aws",
        display_name="API Gateway Stage",
        service="API",
        metrics=(
            _M("Count", "AWS/ApiGateway", "Sum", "Stage"),
            _M("4XXError", "AWS/ApiGateway", "Sum", "Stage"),
            _M("Latency", "AWS/ApiGateway", "Average", "Stage"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::CloudFront::Distribution",
        cloud="aws",
        display_name="CloudFront Distribution",
        service="CDN",
        metrics=(
            _M("Requests", "AWS/CloudFront", "Sum", "DistributionId"),
            _M("BytesDownloaded", "AWS/CloudFront", "Sum", "DistributionId"),
            _M("4xxErrorRate", "AWS/CloudFront", "Average", "DistributionId"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::StepFunctions::StateMachine",
        cloud="aws",
        display_name="Step Functions State Machine",
        service="Orchestration",
        metrics=(
            _M("ExecutionsStarted", "AWS/States", "Sum", "StateMachineArn"),
            _M("ExecutionsSucceeded", "AWS/States", "Sum", "StateMachineArn"),
            _M("ExecutionsFailed", "AWS/States", "Sum", "StateMachineArn"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::Glue::Job",
        cloud="aws",
        display_name="Glue Job",
        service="Analytics",
        metrics=(
            _M("glue.driver.aggregate.bytesRead", "Glue", "Sum", "JobName"),
            _M("glue.driver.aggregate.elapsedTime", "Glue", "Average", "JobName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::MSK::Cluster",
        cloud="aws",
        display_name="MSK Kafka Cluster",
        service="Streaming",
        metrics=(
            _M("BytesInPerSec", "AWS/Kafka", "Sum", "Cluster Name"),
            _M("BytesOutPerSec", "AWS/Kafka", "Sum", "Cluster Name"),
            _M("KafkaDataLogsDiskUsed", "AWS/Kafka", "Average", "Cluster Name"),
        ),
        typical_monthly_cost_usd=400.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::SageMaker::Endpoint",
        cloud="aws",
        display_name="SageMaker Endpoint",
        service="ML",
        metrics=(
            _M("Invocations", "AWS/SageMaker", "Sum", "EndpointName"),
            _M("ModelLatency", "AWS/SageMaker", "Average", "EndpointName"),
            _M("CPUUtilization", "AWS/SageMaker", "Average", "EndpointName"),
        ),
        typical_monthly_cost_usd=250.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::EMR::Cluster",
        cloud="aws",
        display_name="EMR Cluster",
        service="Analytics",
        metrics=(
            _M("YARNMemoryAvailablePercentage", "AWS/ElasticMapReduce", "Average", "JobFlowId"),
            _M("ContainerPendingRatio", "AWS/ElasticMapReduce", "Average", "JobFlowId"),
            _M("AppsRunning", "AWS/ElasticMapReduce", "Average", "JobFlowId"),
        ),
        typical_monthly_cost_usd=500.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::DMS::ReplicationInstance",
        cloud="aws",
        display_name="DMS Replication Instance",
        service="Migration",
        metrics=(
            _M("CPUUtilization", "AWS/DMS", "Average", "ReplicationInstanceIdentifier"),
            _M("FreeableMemory", "AWS/DMS", "Average", "ReplicationInstanceIdentifier"),
            _M("CDCLatencySource", "AWS/DMS", "Average", "ReplicationInstanceIdentifier"),
        ),
        typical_monthly_cost_usd=80.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::Neptune::DBCluster",
        cloud="aws",
        display_name="Neptune DB Cluster",
        service="Database",
        metrics=(
            _M("CPUUtilization", "AWS/Neptune", "Average", "DBClusterIdentifier"),
            _M("DatabaseConnections", "AWS/Neptune", "Average", "DBClusterIdentifier"),
            _M("BufferCacheHitRatio", "AWS/Neptune", "Average", "DBClusterIdentifier"),
        ),
        typical_monthly_cost_usd=200.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::DocDB::DBCluster",
        cloud="aws",
        display_name="DocumentDB Cluster",
        service="Database",
        metrics=(
            _M("CPUUtilization", "AWS/DocDB", "Average", "DBClusterIdentifier"),
            _M("DatabaseConnections", "AWS/DocDB", "Average", "DBClusterIdentifier"),
            _M("BufferCacheHitRatio", "AWS/DocDB", "Average", "DBClusterIdentifier"),
        ),
        typical_monthly_cost_usd=180.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::WorkSpaces::Workspace",
        cloud="aws",
        display_name="WorkSpaces Workspace",
        service="End User Computing",
        metrics=(
            _M("Available", "AWS/WorkSpaces", "Average", "WorkspaceId"),
            _M("InSessionLatency", "AWS/WorkSpaces", "Average", "WorkspaceId"),
            _M("SessionLaunchTime", "AWS/WorkSpaces", "Average", "WorkspaceId"),
        ),
        typical_monthly_cost_usd=35.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::KinesisFirehose::DeliveryStream",
        cloud="aws",
        display_name="Kinesis Firehose Delivery Stream",
        service="Streaming",
        metrics=(
            _M("IncomingBytes", "AWS/Firehose", "Sum", "DeliveryStreamName"),
            _M("IncomingRecords", "AWS/Firehose", "Sum", "DeliveryStreamName"),
            _M("DeliveryToS3.Success", "AWS/Firehose", "Sum", "DeliveryStreamName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::AppSync::GraphQLApi",
        cloud="aws",
        display_name="AppSync GraphQL API",
        service="API",
        metrics=(
            _M("4XXError", "AWS/AppSync", "Sum", "GraphQLAPIId"),
            _M("5XXError", "AWS/AppSync", "Sum", "GraphQLAPIId"),
            _M("Latency", "AWS/AppSync", "Average", "GraphQLAPIId"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::Events::Rule",
        cloud="aws",
        display_name="EventBridge Rule",
        service="Orchestration",
        metrics=(
            _M("TriggeredRules", "AWS/Events", "Sum", "RuleName"),
            _M("Invocations", "AWS/Events", "Sum", "RuleName"),
            _M("FailedInvocations", "AWS/Events", "Sum", "RuleName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::ElasticBeanstalk::Environment",
        cloud="aws",
        display_name="Elastic Beanstalk Environment",
        service="Compute",
        metrics=(
            _M("EnvironmentHealth", "AWS/ElasticBeanstalk", "Average", "EnvironmentName"),
            _M("ApplicationRequestsTotal", "AWS/ElasticBeanstalk", "Sum", "EnvironmentName"),
            _M("CPUUtilization", "AWS/ElasticBeanstalk", "Average", "EnvironmentName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::CodeBuild::Project",
        cloud="aws",
        display_name="CodeBuild Project",
        service="CI/CD",
        metrics=(
            _M("Builds", "AWS/CodeBuild", "Sum", "ProjectName"),
            _M("SucceededBuilds", "AWS/CodeBuild", "Sum", "ProjectName"),
            _M("Duration", "AWS/CodeBuild", "Average", "ProjectName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::Transfer::Server",
        cloud="aws",
        display_name="Transfer Family Server",
        service="Storage",
        metrics=(
            _M("FilesIn", "AWS/Transfer", "Sum", "ServerId"),
            _M("FilesOut", "AWS/Transfer", "Sum", "ServerId"),
            _M("BytesIn", "AWS/Transfer", "Sum", "ServerId"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::WAFv2::WebACL",
        cloud="aws",
        display_name="WAFv2 Web ACL",
        service="Security",
        metrics=(
            _M("AllowedRequests", "AWS/WAFV2", "Sum", "WebACL"),
            _M("BlockedRequests", "AWS/WAFV2", "Sum", "WebACL"),
            _M("CountedRequests", "AWS/WAFV2", "Sum", "WebACL"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::S3::Bucket",
        cloud="aws",
        display_name="S3 Bucket",
        service="Storage",
        metrics=(
            _M("NumberOfObjects", "AWS/S3", "Average", "BucketName"),
            _M("BucketSizeBytes", "AWS/S3", "Average", "BucketName"),
            _M("AllRequests", "AWS/S3", "Sum", "BucketName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::Cognito::UserPool",
        cloud="aws",
        display_name="Cognito User Pool",
        service="Identity",
        metrics=(
            _M("SignInSuccesses", "AWS/Cognito", "Sum", "UserPool"),
            _M("TokenRefreshSuccesses", "AWS/Cognito", "Sum", "UserPool"),
            _M("SignUpSuccesses", "AWS/Cognito", "Sum", "UserPool"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::IoT::Thing",
        cloud="aws",
        display_name="IoT Core Thing",
        service="IoT",
        metrics=(
            _M("PublishIn.Success", "AWS/IoT", "Sum", "Protocol"),
            _M("PublishOut.Success", "AWS/IoT", "Sum", "Protocol"),
            _M("Connect.Success", "AWS/IoT", "Sum", "Protocol"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::MediaLive::Channel",
        cloud="aws",
        display_name="MediaLive Channel",
        service="Media",
        metrics=(
            _M("ActiveOutputs", "AWS/MediaLive", "Average", "ChannelId"),
            _M("DroppedFrames", "AWS/MediaLive", "Sum", "ChannelId"),
            _M("NetworkIn", "AWS/MediaLive", "Sum", "ChannelId"),
        ),
        typical_monthly_cost_usd=600.0,
    ),
    ResourceTypeSpec(
        type_id="AWS::Batch::JobQueue",
        cloud="aws",
        display_name="Batch Job Queue",
        service="Compute",
        metrics=(
            _M("PendingJobCount", "AWS/Batch", "Average", "JobQueueName"),
            _M("RunnableJobCount", "AWS/Batch", "Average", "JobQueueName"),
            _M("RunningJobCount", "AWS/Batch", "Average", "JobQueueName"),
        ),
    ),
    ResourceTypeSpec(
        type_id="AWS::Route53::HostedZone",
        cloud="aws",
        display_name="Route 53 Hosted Zone",
        service="DNS",
        metrics=(
            _M("DNSQueries", "AWS/Route53", "Sum", "HostedZoneId"),
        ),
        typical_monthly_cost_usd=0.5,
    ),
]
