from __future__ import annotations

from core.registry.models import MetricSpec, ResourceTypeSpec

_M = MetricSpec

AZURE_RESOURCE_TYPES: list[ResourceTypeSpec] = [
    ResourceTypeSpec(
        type_id="microsoft.compute/virtualmachines",
        cloud="azure",
        display_name="Virtual Machine",
        service="Compute",
        metrics=(
            _M("Percentage CPU", "microsoft.compute/virtualmachines", "Average", ""),
            _M("Network In Total", "microsoft.compute/virtualmachines", "Total", ""),
            _M("Network Out Total", "microsoft.compute/virtualmachines", "Total", ""),
        ),
        actions=("delete", "resize", "stop", "snapshot_delete", "convert_spot"),
        typical_monthly_cost_usd=50.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.compute/virtualmachinescalesets",
        cloud="azure",
        display_name="VM Scale Set",
        service="Compute",
        metrics=(
            _M(
                "Percentage CPU",
                "microsoft.compute/virtualmachinescalesets",
                "Average",
                "",
            ),
            _M(
                "Network In Total",
                "microsoft.compute/virtualmachinescalesets",
                "Total",
                "",
            ),
            _M(
                "Network Out Total",
                "microsoft.compute/virtualmachinescalesets",
                "Total",
                "",
            ),
        ),
        actions=("delete", "resize", "reduce_nodes"),
        typical_monthly_cost_usd=150.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.compute/disks",
        cloud="azure",
        display_name="Managed Disk",
        service="Storage",
        metrics=(
            _M(
                "Composite Disk Read Operations/sec",
                "microsoft.compute/disks",
                "Average",
                "",
            ),
            _M(
                "Composite Disk Write Operations/sec",
                "microsoft.compute/disks",
                "Average",
                "",
            ),
        ),
        actions=("delete", "snapshot_delete", "archive"),
        typical_monthly_cost_usd=15.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.sql/servers/databases",
        cloud="azure",
        display_name="Azure SQL Database",
        service="Database",
        metrics=(
            _M("cpu_percent", "microsoft.sql/servers/databases", "Average", ""),
            _M("connection_successful", "microsoft.sql/servers/databases", "Total", ""),
            _M("storage_percent", "microsoft.sql/servers/databases", "Average", ""),
        ),
        actions=("delete", "resize", "snapshot_delete"),
        typical_monthly_cost_usd=150.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.sql/managedinstances",
        cloud="azure",
        display_name="SQL Managed Instance",
        service="Database",
        metrics=(
            _M("avg_cpu_percent", "microsoft.sql/managedinstances", "Average", ""),
            _M(
                "storage_space_used_mb", "microsoft.sql/managedinstances", "Average", ""
            ),
        ),
        actions=("delete", "resize", "snapshot_delete"),
        typical_monthly_cost_usd=500.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.web/serverfarms",
        cloud="azure",
        display_name="App Service Plan",
        service="Compute",
        metrics=(
            _M("CpuPercentage", "microsoft.web/serverfarms", "Average", ""),
            _M("MemoryPercentage", "microsoft.web/serverfarms", "Average", ""),
            _M("HttpQueueLength", "microsoft.web/serverfarms", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=75.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.web/sites",
        cloud="azure",
        display_name="App Service / Function App",
        service="Compute",
        metrics=(
            _M("CpuTime", "microsoft.web/sites", "Total", ""),
            _M("Requests", "microsoft.web/sites", "Total", ""),
            _M("BytesReceived", "microsoft.web/sites", "Total", ""),
        ),
        actions=("delete", "stop"),
        typical_monthly_cost_usd=55.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.containerservice/managedclusters",
        cloud="azure",
        display_name="AKS Cluster",
        service="Compute",
        metrics=(
            _M(
                "node_cpu_usage_percentage",
                "microsoft.containerservice/managedclusters",
                "Average",
                "",
            ),
            _M(
                "node_memory_rss_percentage",
                "microsoft.containerservice/managedclusters",
                "Average",
                "",
            ),
            _M(
                "kube_node_status_allocatable_cpu_cores",
                "microsoft.containerservice/managedclusters",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize", "reduce_nodes"),
        typical_monthly_cost_usd=73.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.containerinstance/containergroups",
        cloud="azure",
        display_name="Container Instance",
        service="Compute",
        metrics=(
            _M(
                "CpuUsage", "microsoft.containerinstance/containergroups", "Average", ""
            ),
            _M(
                "MemoryUsage",
                "microsoft.containerinstance/containergroups",
                "Average",
                "",
            ),
            _M(
                "NetworkBytesReceivedPerSecond",
                "microsoft.containerinstance/containergroups",
                "Average",
                "",
            ),
        ),
        actions=("delete", "stop"),
        typical_monthly_cost_usd=30.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.cache/redis",
        cloud="azure",
        display_name="Azure Cache for Redis",
        service="Cache",
        metrics=(
            _M("connectedclients", "microsoft.cache/redis", "Average", ""),
            _M("cachehits", "microsoft.cache/redis", "Total", ""),
            _M("cachemisses", "microsoft.cache/redis", "Total", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=60.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.documentdb/databaseaccounts",
        cloud="azure",
        display_name="Cosmos DB Account",
        service="Database",
        metrics=(
            _M("TotalRequests", "microsoft.documentdb/databaseaccounts", "Total", ""),
            _M(
                "NormalizedRUConsumption",
                "microsoft.documentdb/databaseaccounts",
                "Average",
                "",
            ),
            _M(
                "ServerSideLatency",
                "microsoft.documentdb/databaseaccounts",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize", "reduce_replicas"),
        typical_monthly_cost_usd=200.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.storage/storageaccounts",
        cloud="azure",
        display_name="Storage Account",
        service="Storage",
        metrics=(
            _M("Transactions", "microsoft.storage/storageaccounts", "Total", ""),
            _M("Ingress", "microsoft.storage/storageaccounts", "Total", ""),
            _M("Egress", "microsoft.storage/storageaccounts", "Total", ""),
        ),
        actions=("delete", "archive"),
        typical_monthly_cost_usd=10.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.containerservice/managedclusters/agentpools",
        cloud="azure",
        display_name="AKS Node Pool",
        service="Compute",
        metrics=(
            _M(
                "node_cpu_usage_percentage",
                "microsoft.containerservice/managedclusters/agentpools",
                "Average",
                "",
            ),
            _M(
                "node_memory_rss_percentage",
                "microsoft.containerservice/managedclusters/agentpools",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize", "reduce_nodes"),
        typical_monthly_cost_usd=100.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.eventhub/namespaces",
        cloud="azure",
        display_name="Event Hubs Namespace",
        service="Messaging",
        metrics=(
            _M("IncomingMessages", "microsoft.eventhub/namespaces", "Total", ""),
            _M("OutgoingMessages", "microsoft.eventhub/namespaces", "Total", ""),
            _M("ActiveConnections", "microsoft.eventhub/namespaces", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=25.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.servicebus/namespaces",
        cloud="azure",
        display_name="Service Bus Namespace",
        service="Messaging",
        metrics=(
            _M("IncomingMessages", "microsoft.servicebus/namespaces", "Total", ""),
            _M("OutgoingMessages", "microsoft.servicebus/namespaces", "Total", ""),
            _M("ActiveConnections", "microsoft.servicebus/namespaces", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=10.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.web/sites/functions",
        cloud="azure",
        display_name="Azure Functions",
        service="Compute",
        metrics=(
            _M("FunctionExecutionCount", "microsoft.web/sites/functions", "Total", ""),
            _M("FunctionExecutionUnits", "microsoft.web/sites/functions", "Total", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=5.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.apimanagement/service",
        cloud="azure",
        display_name="API Management Service",
        service="API",
        metrics=(
            _M("TotalRequests", "microsoft.apimanagement/service", "Total", ""),
            _M("SuccessfulRequests", "microsoft.apimanagement/service", "Total", ""),
            _M("Capacity", "microsoft.apimanagement/service", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=200.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/applicationgateways",
        cloud="azure",
        display_name="Application Gateway",
        service="Networking",
        metrics=(
            _M("TotalRequests", "microsoft.network/applicationgateways", "Total", ""),
            _M(
                "CurrentConnections",
                "microsoft.network/applicationgateways",
                "Average",
                "",
            ),
            _M("Throughput", "microsoft.network/applicationgateways", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=120.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/loadbalancers",
        cloud="azure",
        display_name="Load Balancer",
        service="Networking",
        metrics=(
            _M("PacketCount", "microsoft.network/loadbalancers", "Total", ""),
            _M("ByteCount", "microsoft.network/loadbalancers", "Total", ""),
            _M("AllocatedSnatPorts", "microsoft.network/loadbalancers", "Average", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=18.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.databricks/workspaces",
        cloud="azure",
        display_name="Azure Databricks Workspace",
        service="Analytics",
        metrics=(
            _M(
                "autoOptimizeClusterUtilization",
                "microsoft.databricks/workspaces",
                "Average",
                "",
            ),
            _M("numActiveClusters", "microsoft.databricks/workspaces", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=400.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.hdinsight/clusters",
        cloud="azure",
        display_name="HDInsight Cluster",
        service="Analytics",
        metrics=(
            _M("GatewayRequests", "microsoft.hdinsight/clusters", "Total", ""),
            _M(
                "CategorizedGatewayRequests",
                "microsoft.hdinsight/clusters",
                "Total",
                "",
            ),
        ),
        actions=("delete", "resize", "reduce_nodes"),
        typical_monthly_cost_usd=300.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.logic/workflows",
        cloud="azure",
        display_name="Logic App Workflow",
        service="Orchestration",
        metrics=(
            _M("RunsStarted", "microsoft.logic/workflows", "Total", ""),
            _M("RunsCompleted", "microsoft.logic/workflows", "Total", ""),
            _M("RunsFailed", "microsoft.logic/workflows", "Total", ""),
        ),
        actions=("delete", "stop"),
        typical_monthly_cost_usd=5.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.cognitiveservices/accounts",
        cloud="azure",
        display_name="Cognitive Services / Azure OpenAI",
        service="AI",
        metrics=(
            _M("TotalCalls", "microsoft.cognitiveservices/accounts", "Total", ""),
            _M("TotalErrors", "microsoft.cognitiveservices/accounts", "Total", ""),
            _M("Latency", "microsoft.cognitiveservices/accounts", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=30.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.search/searchservices",
        cloud="azure",
        display_name="Azure AI Search",
        service="Search",
        metrics=(
            _M(
                "SearchQueriesPerSecond",
                "microsoft.search/searchservices",
                "Average",
                "",
            ),
            _M(
                "ThrottledSearchQueriesPercentage",
                "microsoft.search/searchservices",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=250.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.streamanalytics/streamingjobs",
        cloud="azure",
        display_name="Stream Analytics Job",
        service="Analytics",
        metrics=(
            _M("InputEvents", "microsoft.streamanalytics/streamingjobs", "Total", ""),
            _M("OutputEvents", "microsoft.streamanalytics/streamingjobs", "Total", ""),
            _M(
                "ResourceUtilization",
                "microsoft.streamanalytics/streamingjobs",
                "Average",
                "",
            ),
        ),
        actions=("delete", "stop"),
        typical_monthly_cost_usd=80.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.datafactory/factories",
        cloud="azure",
        display_name="Azure Data Factory",
        service="Integration",
        metrics=(
            _M("PipelineRunsStarted", "microsoft.datafactory/factories", "Total", ""),
            _M("ActivityRunsStarted", "microsoft.datafactory/factories", "Total", ""),
            _M("TriggerRunsStarted", "microsoft.datafactory/factories", "Total", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=50.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/natgateways",
        cloud="azure",
        display_name="NAT Gateway",
        service="Networking",
        metrics=(
            _M("ByteCount", "microsoft.network/natgateways", "Total", ""),
            _M("PacketCount", "microsoft.network/natgateways", "Total", ""),
            _M("SNATConnectionCount", "microsoft.network/natgateways", "Total", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=32.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/virtualnetworkgateways",
        cloud="azure",
        display_name="VPN Gateway",
        service="Networking",
        metrics=(
            _M(
                "TunnelIngressBytes",
                "microsoft.network/virtualnetworkgateways",
                "Total",
                "",
            ),
            _M(
                "TunnelEgressBytes",
                "microsoft.network/virtualnetworkgateways",
                "Total",
                "",
            ),
            _M(
                "P2SConnectionCount",
                "microsoft.network/virtualnetworkgateways",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=140.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/azurefirewalls",
        cloud="azure",
        display_name="Azure Firewall",
        service="Security",
        metrics=(
            _M("DataProcessed", "microsoft.network/azurefirewalls", "Total", ""),
            _M("FirewallHealth", "microsoft.network/azurefirewalls", "Average", ""),
            _M("Throughput", "microsoft.network/azurefirewalls", "Average", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=900.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/frontdoors",
        cloud="azure",
        display_name="Azure Front Door",
        service="CDN",
        metrics=(
            _M("RequestCount", "microsoft.network/frontdoors", "Total", ""),
            _M("TotalLatency", "microsoft.network/frontdoors", "Average", ""),
            _M("RequestSize", "microsoft.network/frontdoors", "Total", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=35.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/expressroutecircuits",
        cloud="azure",
        display_name="ExpressRoute Circuit",
        service="Networking",
        metrics=(
            _M(
                "BitsInPerSecond",
                "microsoft.network/expressroutecircuits",
                "Average",
                "",
            ),
            _M(
                "BitsOutPerSecond",
                "microsoft.network/expressroutecircuits",
                "Average",
                "",
            ),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=500.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.network/publicipaddresses",
        cloud="azure",
        display_name="Public IP Address",
        service="Networking",
        metrics=(
            _M("ByteCount", "microsoft.network/publicipaddresses", "Total", ""),
            _M("PacketCount", "microsoft.network/publicipaddresses", "Total", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=4.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.dbformysql/flexibleservers",
        cloud="azure",
        display_name="Azure Database for MySQL",
        service="Database",
        metrics=(
            _M("cpu_percent", "microsoft.dbformysql/flexibleservers", "Average", ""),
            _M(
                "active_connections",
                "microsoft.dbformysql/flexibleservers",
                "Average",
                "",
            ),
            _M(
                "storage_percent", "microsoft.dbformysql/flexibleservers", "Average", ""
            ),
        ),
        actions=("delete", "resize", "stop", "snapshot_delete"),
        typical_monthly_cost_usd=100.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.dbforpostgresql/flexibleservers",
        cloud="azure",
        display_name="Azure Database for PostgreSQL",
        service="Database",
        metrics=(
            _M(
                "cpu_percent",
                "microsoft.dbforpostgresql/flexibleservers",
                "Average",
                "",
            ),
            _M(
                "active_connections",
                "microsoft.dbforpostgresql/flexibleservers",
                "Average",
                "",
            ),
            _M(
                "storage_percent",
                "microsoft.dbforpostgresql/flexibleservers",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize", "stop", "snapshot_delete"),
        typical_monthly_cost_usd=100.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.dbformariadb/servers",
        cloud="azure",
        display_name="Azure Database for MariaDB",
        service="Database",
        metrics=(
            _M("cpu_percent", "microsoft.dbformariadb/servers", "Average", ""),
            _M("active_connections", "microsoft.dbformariadb/servers", "Average", ""),
            _M("storage_percent", "microsoft.dbformariadb/servers", "Average", ""),
        ),
        actions=("delete", "resize", "stop", "snapshot_delete"),
        typical_monthly_cost_usd=80.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.synapse/workspaces/sqlpools",
        cloud="azure",
        display_name="Synapse SQL Pool",
        service="Analytics",
        metrics=(
            _M(
                "DWUUsedPercent", "microsoft.synapse/workspaces/sqlpools", "Average", ""
            ),
            _M("ActiveQueries", "microsoft.synapse/workspaces/sqlpools", "Total", ""),
            _M(
                "ConnectionsBlockedByFirewall",
                "microsoft.synapse/workspaces/sqlpools",
                "Total",
                "",
            ),
        ),
        actions=("delete", "resize", "snapshot_delete"),
        typical_monthly_cost_usd=600.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.machinelearningservices/workspaces/onlineendpoints",
        cloud="azure",
        display_name="Azure ML Online Endpoint",
        service="ML",
        metrics=(
            _M(
                "RequestsPerMinute",
                "microsoft.machinelearningservices/workspaces/onlineendpoints",
                "Average",
                "",
            ),
            _M(
                "RequestLatency",
                "microsoft.machinelearningservices/workspaces/onlineendpoints",
                "Average",
                "",
            ),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=150.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.batch/batchaccounts",
        cloud="azure",
        display_name="Batch Account",
        service="Compute",
        metrics=(
            _M("TaskStartEvent", "microsoft.batch/batchaccounts", "Total", ""),
            _M("CoreCount", "microsoft.batch/batchaccounts", "Average", ""),
            _M("IdleNodeCount", "microsoft.batch/batchaccounts", "Average", ""),
        ),
        actions=("delete",),
        typical_monthly_cost_usd=50.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.devices/iothubs",
        cloud="azure",
        display_name="IoT Hub",
        service="IoT",
        metrics=(
            _M(
                "d2c.telemetry.ingress.allProtocol",
                "microsoft.devices/iothubs",
                "Total",
                "",
            ),
            _M("connectedDeviceCount", "microsoft.devices/iothubs", "Average", ""),
            _M("totalDeviceCount", "microsoft.devices/iothubs", "Average", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=25.0,
    ),
    ResourceTypeSpec(
        type_id="microsoft.signalrservice/signalr",
        cloud="azure",
        display_name="Azure SignalR Service",
        service="Messaging",
        metrics=(
            _M("ConnectionCount", "microsoft.signalrservice/signalr", "Average", ""),
            _M("MessageCount", "microsoft.signalrservice/signalr", "Total", ""),
            _M("InboundTraffic", "microsoft.signalrservice/signalr", "Total", ""),
        ),
        actions=("delete", "resize"),
        typical_monthly_cost_usd=50.0,
    ),
]
