"""
Azure Function entrypoint for Argus (Timer trigger).

The function is triggered on a schedule by Azure Function's built-in timer trigger.
Deploy with the Bicep template in deploy/azure/function-app.bicep.

Environment variables (set in Azure Function App Configuration):
  AZURE_SUBSCRIPTION_IDS          Comma-separated subscription IDs to scan (required)
  AZURE_LOG_ANALYTICS_WORKSPACE_ID Log Analytics workspace ID (optional — for Activity Log KQL)
  AI_PROVIDER                     "anthropic" | "azure_openai" (default: azure_openai)
  ANTHROPIC_API_KEY               Required when AI_PROVIDER=anthropic
  AZURE_OPENAI_ENDPOINT           Required when AI_PROVIDER=azure_openai
  AZURE_OPENAI_DEPLOYMENT         GPT-4o deployment name (default: gpt-4o)
  IGNORE_REGIONS                  Comma-separated regions to exclude (default: empty)
  SLACK_WEBHOOK_URL               Slack incoming webhook URL
  DRY_RUN                         "true" to skip Slack post (default: false)
  LOG_LEVEL                       DEBUG | INFO | WARNING | ERROR (default: INFO)
"""
from __future__ import annotations

import logging
import os

from adapters.azure.adapter import AzureAdapter
from core.agent.loop import AgentLoop
from core.reports.delivery import post_to_slack
from core.reports.generator import build_report, build_slack_payload

logger = logging.getLogger(__name__)


def main(mytimer) -> None:
    """
    Azure Function timer trigger entry point.

    `mytimer` is an azure.functions.TimerRequest object injected by the runtime.
    The function name and schedule are defined in function.json (generated by
    the Bicep template / func CLI).
    """
    if mytimer.past_due:
        logger.warning("Timer is past due — running scan now")

    cloud = "azure"
    ignore_regions = [
        r.strip()
        for r in os.environ.get("IGNORE_REGIONS", "").split(",")
        if r.strip()
    ]

    subscription_ids_raw = os.environ.get("AZURE_SUBSCRIPTION_IDS", "").strip()
    if not subscription_ids_raw:
        logger.error("AZURE_SUBSCRIPTION_IDS is not set — cannot scan")
        return

    subscription_ids = [s.strip() for s in subscription_ids_raw.split(",") if s.strip()]

    logger.info(
        "scan_start cloud=%s subscriptions=%s ignore_regions=%s",
        cloud, subscription_ids, ignore_regions,
    )

    ai_provider = _build_ai_provider()
    adapter = AzureAdapter.from_env()

    loop = AgentLoop(ai_provider=ai_provider, cloud_adapter=adapter)
    findings, executive_summary = loop.run(
        cloud=cloud,
        ignore_regions=ignore_regions,
        accounts=[{"id": sid, "name": sid} for sid in subscription_ids],
    )

    report = build_report(
        findings,
        cloud=cloud,
        executive_summary=executive_summary,
        accounts_scanned=subscription_ids,
    )

    payload = build_slack_payload(report)
    post_to_slack(payload)

    logger.info(
        "scan_complete findings=%d total_waste_usd=%.2f scan_id=%s",
        report["findings_count"],
        report["total_estimated_waste_usd"],
        report["scan_id"],
    )


def _build_ai_provider():
    provider_name = os.environ.get("AI_PROVIDER", "azure_openai").lower()
    if provider_name == "anthropic":
        from ai.anthropic import AnthropicProvider
        return AnthropicProvider()
    from ai.azure_openai import AzureOpenAIProvider
    return AzureOpenAIProvider()
