"""
Azure Function entrypoint for Argus (Timer trigger).

The function is triggered on a schedule by Azure Function's built-in timer trigger.
Deploy with the Bicep template in deploy/azure/function-app.bicep.

Environment variables (set in Azure Function App Configuration):
  AZURE_SUBSCRIPTION_IDS           Comma-separated subscription IDs to scan (required)
  AZURE_LOG_ANALYTICS_WORKSPACE_ID Log Analytics workspace ID
                                   (optional — for Activity Log KQL)
  AI_PROVIDER                      "anthropic" | "azure_openai" (default: azure_openai)
  ANTHROPIC_API_KEY                Required when AI_PROVIDER=anthropic
  AZURE_OPENAI_ENDPOINT            Required when AI_PROVIDER=azure_openai
  AZURE_OPENAI_DEPLOYMENT          GPT-4o deployment name (default: gpt-4o)
  IGNORE_REGIONS                   Comma-separated regions to exclude (default: empty)
  SLACK_WEBHOOK_URL                Slack incoming webhook URL
  DRY_RUN                         "true" to skip Slack post (default: false)
  REPORT_STORAGE_ACCOUNT          Azure Storage account name for full reports (optional)
  REPORT_STORAGE_CONTAINER        Blob container name (default: argus-reports)
  REPORT_URL_EXPIRY               SAS URL expiry in seconds (default: 604800 = 7 days)
  LOG_LEVEL                        DEBUG | INFO | WARNING | ERROR (default: INFO)
"""

from __future__ import annotations

import json
import os
from datetime import datetime, timedelta, timezone
from typing import Any

import structlog

from adapters.azure.adapter import AzureAdapter
from core.agent.loop import AgentLoop
from core.log import configure_logging
from core.reports.delivery import (
    SlackDeliveryError,
    post_to_slack,
    save_reports_locally,
)
from core.reports.generator import build_report, build_slack_payload
from core.reports.html import build_html_report
from core.validation import ConfigurationError, validate_environment

configure_logging()
logger = structlog.get_logger(__name__)


def main(mytimer: Any) -> None:
    """
    Azure Function timer trigger entry point.

    `mytimer` is an azure.functions.TimerRequest object injected by the runtime.
    The function name and schedule are defined in function.json (generated by
    the Bicep template / func CLI).
    """
    if mytimer.past_due:
        logger.warning("Timer is past due — running scan now")

    cloud = "azure"
    try:
        validate_environment(cloud)
    except ConfigurationError as exc:
        logger.error("startup_validation_failed", error=str(exc))
        return

    ignore_regions = [
        r.strip() for r in os.environ.get("IGNORE_REGIONS", "").split(",") if r.strip()
    ]

    subscription_ids_raw = os.environ.get("AZURE_SUBSCRIPTION_IDS", "").strip()

    subscription_ids = [s.strip() for s in subscription_ids_raw.split(",") if s.strip()]

    structlog.contextvars.bind_contextvars(
        cloud=cloud, account_id=",".join(subscription_ids)
    )
    logger.info(
        "scan_start", subscriptions=subscription_ids, ignore_regions=ignore_regions
    )

    ai_provider = _build_ai_provider()
    adapter = AzureAdapter.from_env()

    loop = AgentLoop(ai_provider=ai_provider, cloud_adapter=adapter)
    findings, executive_summary = loop.run(
        cloud=cloud,
        ignore_regions=ignore_regions,
        accounts=[{"id": sid, "name": sid} for sid in subscription_ids],
    )

    report = build_report(
        findings,
        cloud=cloud,
        executive_summary=executive_summary,
        accounts_scanned=subscription_ids,
    )

    storage_account = os.environ.get("REPORT_STORAGE_ACCOUNT", "").strip()
    report_url: str | None = None
    if storage_account:
        report_url = _save_reports_to_blob(report, storage_account)
    else:
        save_reports_locally(report)

    structlog.contextvars.bind_contextvars(scan_id=report["scan_id"])
    payload = build_slack_payload(report, report_url=report_url)
    try:
        post_to_slack(payload)
    except (SlackDeliveryError, OSError) as exc:
        logger.error("slack_delivery_failed", error=str(exc))

    logger.info(
        "scan_complete",
        findings=report["findings_count"],
        total_waste_usd=round(report["total_estimated_waste_usd"], 2),
    )


def _build_ai_provider() -> Any:
    provider_name = os.environ.get("AI_PROVIDER", "azure_openai").lower()
    if provider_name == "anthropic":
        from ai.anthropic import AnthropicProvider

        return AnthropicProvider()
    from ai.azure_openai import AzureOpenAIProvider

    return AzureOpenAIProvider()


def _save_reports_to_blob(report: dict[str, Any], storage_account: str) -> str | None:
    """Upload JSON + HTML reports to Azure Blob. Returns a SAS URL for the HTML."""
    try:
        from azure.core.exceptions import (  # type: ignore[import-untyped]
            AzureError,
            ResourceExistsError,
        )
        from azure.identity import (
            DefaultAzureCredential,  # type: ignore[import-untyped]
        )
        from azure.storage.blob import (  # type: ignore[import-untyped]
            BlobSasPermissions,
            BlobServiceClient,
            generate_blob_sas,
        )
    except ImportError:
        logger.error(
            "azure-storage-blob or azure-identity is not installed "
            "— skipping Blob upload. "
            "Run: pip install azure-storage-blob azure-identity"
        )
        return None

    container = os.environ.get("REPORT_STORAGE_CONTAINER", "argus-reports")
    expiry_seconds = int(os.environ.get("REPORT_URL_EXPIRY", "604800"))
    now = datetime.now(tz=timezone.utc)
    prefix = f"reports/{report['cloud']}/{now.strftime('%Y/%m/%d')}/{report['scan_id']}"
    json_key = f"{prefix}.json"
    html_key = f"{prefix}.html"

    try:
        credential = DefaultAzureCredential()
        account_url = f"https://{storage_account}.blob.core.windows.net"
        client = BlobServiceClient(account_url=account_url, credential=credential)
        container_client = client.get_container_client(container)

        try:
            container_client.create_container()
        except ResourceExistsError:
            pass

        container_client.upload_blob(
            json_key,
            json.dumps(report, indent=2, default=str).encode("utf-8"),
            content_settings={"content_type": "application/json"},
            overwrite=True,
        )
        logger.info(
            "json_report_saved",
            location=f"{storage_account}/{container}/{json_key}",
        )

        container_client.upload_blob(
            html_key,
            build_html_report(report).encode("utf-8"),
            content_settings={"content_type": "text/html; charset=utf-8"},
            overwrite=True,
        )
        logger.info(
            "html_report_saved",
            location=f"{storage_account}/{container}/{html_key}",
        )

        # SAS token scoped to just this blob
        user_delegation_key = client.get_user_delegation_key(
            key_start_time=now,
            key_expiry_time=now + timedelta(seconds=expiry_seconds),
        )
        sas_token = generate_blob_sas(
            account_name=storage_account,
            container_name=container,
            blob_name=html_key,
            user_delegation_key=user_delegation_key,
            permission=BlobSasPermissions(read=True),
            expiry=now + timedelta(seconds=expiry_seconds),
        )
        url = f"{account_url}/{container}/{html_key}?{sas_token}"
        logger.info("sas_url_generated", expires_in_seconds=expiry_seconds)
        return url
    except AzureError as exc:
        logger.error("blob_upload_failed", error=str(exc))
        return None
